#!/d/Programs/Python/Python37/python
def processArray(a):

if __name__ == "__main__":
    a = []
    while True:
        x = int(input())
        if x < 0:
            break
        a.append(x)
    processArray(a)
